# Generated by Django 5.1 on 2024-08-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=64, verbose_name='电影名')),
                ('releaseInfo', models.CharField(max_length=64, null=True, verbose_name='上映时间')),
                ('movieScoring', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='评分')),
                ('commentNumber', models.IntegerField(verbose_name='评论人数')),
                ('mainActor', models.CharField(max_length=256, verbose_name='主要演员')),
                ('movieType', models.CharField(max_length=128, verbose_name='类型')),
                ('movieCountry', models.CharField(max_length=128, verbose_name='国家/地区')),
            ],
        ),
    ]
