# Generated by Django 5.1 on 2024-08-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_movieinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieShortComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=64, verbose_name='电影名')),
                ('commentPerson', models.CharField(max_length=64, verbose_name='评论者')),
                ('ratingScale', models.CharField(max_length=16, verbose_name='评分等级')),
                ('commentDate', models.CharField(max_length=32, verbose_name='评论日期')),
                ('starNumber', models.IntegerField(verbose_name='点赞数')),
                ('commentContent', models.TextField(verbose_name='评论内容')),
            ],
        ),
    ]
