# Generated by Django 5.1 on 2024-08-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_movieshortcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movieID',
            field=models.IntegerField(default=1111111, verbose_name='电影ID'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='releaseInfo',
            field=models.CharField(max_length=64, verbose_name='上映时间'),
        ),
    ]
