# Generated by Django 5.1 on 2024-09-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_filmreview_movieinfo_movieurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=64, verbose_name='电影名')),
                ('imageUrl', models.CharField(max_length=128, verbose_name='海报地址')),
                ('movieScoring', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='评分')),
                ('commentNumber', models.IntegerField(verbose_name='评论人数')),
                ('movieType', models.CharField(max_length=64, verbose_name='类型')),
                ('releaseInfo', models.CharField(max_length=64, verbose_name='上映日期')),
                ('duration', models.CharField(max_length=64, verbose_name='片长')),
                ('director', models.CharField(max_length=32, verbose_name='导演')),
                ('actors', models.TextField(verbose_name='主演')),
                ('movieCountry', models.CharField(max_length=32, verbose_name='国家/地区')),
                ('languages', models.CharField(max_length=64, verbose_name='语言')),
                ('introduction', models.TextField(verbose_name='简介')),
            ],
        ),
    ]
