# Generated by Django 5.1 on 2024-09-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_moviedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='languages',
            field=models.CharField(max_length=64, null=True, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='releaseInfo',
            field=models.CharField(max_length=64, null=True, verbose_name='上映日期'),
        ),
    ]
