# Generated by Django 5.1 on 2024-09-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_moviedetails_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='director',
            field=models.CharField(max_length=64, verbose_name='导演'),
        ),
    ]
