# Generated by Django 5.1 on 2024-09-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_moviedetails_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='director',
            field=models.CharField(max_length=128, verbose_name='导演'),
        ),
    ]
