# Generated by Django 5.1 on 2024-09-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_moviedetails_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=64, verbose_name='电影名')),
                ('similarMovies', models.TextField(verbose_name='相似电影列表')),
            ],
        ),
    ]
