# Generated by Django 5.1 on 2024-09-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_similarmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieshortcomment',
            name='commentHandle',
            field=models.TextField(null=True, verbose_name='处理后评论'),
        ),
        migrations.AddField(
            model_name='movieshortcomment',
            name='emotionScale',
            field=models.CharField(max_length=16, null=True, verbose_name='情感度'),
        ),
        migrations.AddField(
            model_name='movieshortcomment',
            name='emotionScored',
            field=models.CharField(max_length=16, null=True, verbose_name='情感得分'),
        ),
        migrations.AddField(
            model_name='movieshortcomment',
            name='emotionTendency',
            field=models.CharField(max_length=8, null=True, verbose_name='情感倾向'),
        ),
    ]
